export const datesWithPostfixes = [
  { id: 1, label: '1st' },
  { id: 2, label: '2nd' },
  { id: 3, label: '3rd' },
  { id: 4, label: '4th' },
  { id: 5, label: '5th' },
  { id: 6, label: '6th' },
  { id: 7, label: '7th' },
  { id: 8, label: '8th' },
  { id: 9, label: '9th' },
  { id: 10, label: '10th' },
  { id: 11, label: '11th' },
  { id: 12, label: '12th' },
  { id: 13, label: '13th' },
  { id: 14, label: '14th' },
  { id: 15, label: '15th' },
  { id: 16, label: '16th' },
  { id: 17, label: '17th' },
  { id: 18, label: '18th' },
  { id: 19, label: '19th' },
  { id: 20, label: '20th' },
  { id: 21, label: '21st' },
  { id: 22, label: '22nd' },
  { id: 23, label: '23rd' },
  { id: 24, label: '24th' },
  { id: 25, label: '25th' },
  { id: 26, label: '26th' },
  { id: 27, label: '27th' },
  { id: 28, label: '28th' },
  { id: 29, label: '29th' },
  { id: 30, label: '30th' },
  { id: 31, label: '31st' },
]

export const totalWeeksInMonth = [
  { id: 1, week: 'First' },
  { id: 2, week: 'Second' },
  { id: 3, week: 'Third' },
  { id: 4, week: 'Fourth' },
  { id: 5, week: 'Fifth' },
]

export const days = [
  { id: 1, day: 'Monday' },
  { id: 2, day: 'Tuesday' },
  { id: 3, day: 'Wednesday' },
  { id: 4, day: 'Thursday' },
  { id: 5, day: 'Friday' },
  { id: 6, day: 'Saturday' },
  { id: 7, day: 'Sunday' },
]

export const months = [
  { id: 1, month: 'January' },
  { id: 2, month: 'February' },
  { id: 3, month: 'March' },
  { id: 4, month: 'April' },
  { id: 5, month: 'May' },
  { id: 6, month: 'June' },
  { id: 7, month: 'July' },
  { id: 8, month: 'August' },
  { id: 9, month: 'September' },
  { id: 10, month: 'October' },
  { id: 11, month: 'November' },
  { id: 12, month: 'December' },
]
